### ISSUE TITLE
[FEATURE] Create Sample Terminal Struct

### ISSUE THREAD

**Issue by HiceS** [RE-Capstone/ConsoleTester#5]
**Describe the solution you'd like**

I would like you to implement a Terminal Struct similar to that of which is described in the below picture taken from the sponsor. This is an example of a possible solution so it's possible that this will not be very useful to us however I would like to implement the example as I believe it may sway our research.

## Todo

- [x] Create a new branch named Feature-[issue name]
- [ ] Create a potential solution 
- [ ] Describe how it can be useful to the project in a PR.
- [ ] Either Merge PR or wait and describe issues.

**Comment by HiceS** [comment]
![Terminal Emulator for testing Rust Command Line Programs SS20 Capstone proposal](https://user-images.githubusercontent.com/6741771/80761546-9f246200-8aef-11ea-9c57-0baf364585cd.png)
