### ISSUE TITLE
[FEATURE] Make Console Test App

### ISSUE THREAD

**Issue by HiceS** [RE-Capstone/ConsoleTester#7]
**Is your feature request related to a problem? Please describe.**

We need to create a test repo with a code base that can implement the Rust Console Emulator so we can test it.

**Describe the solution you'd like**

I would like someone to create a seperate repo that is referenced to this repo via a git sub module that is linked to a empty ` test ` folder that has a empty ` .gitkeep ` file in it while not needed to not create module bloat. 

In this test repo I would like considerable development that would print very pretty and hyper formatted text that works on the user machine that includes ANSI escape codes as well as many other things. Overall this application shouldn't do anything but it should print a bunch of pretty text and be able to be built easily and use a testing framework.

**Describe alternatives you've considered**

I've considered the idea of creating the test as part of the base library which is still a possibility but I would rather someone create an extensive test program rather than a simple one.

## Todo

- [ ] Create another folder in src that runes from main.rs
- [ ] Make a program that prints pretty and formatted text
- [ ] Create a seperate branch on this repo that would link a submodule to the other test repo following the guidelines above
- [ ] Create a PR of the branch.

**Comment by HiceS** [comment]
I'm going to close this for now.
