### ISSUE TITLE
[FEATURE] Rust Doc implementation

### ISSUE THREAD

**Issue by HiceS** [RE-Capstone/ConsoleTester#8]
**Is your feature request related to a problem? Please describe.**

We need a way to create a website that is hosted locally for documentation.

**Describe the solution you'd like**

I would like you to implement a way to create and host the static code documentation as a website locally using pages and regenerating on build.

- Just use Rust Docs [ https://doc.rust-lang.org/rustdoc/what-is-rustdoc.html ](https://doc.rust-lang.org/rustdoc/what-is-rustdoc.html)

## Todo

- [x] Create a new branch
- [x] Add a library that makes sense for generating code sites
- [ ] Make addition to CI or rather build to update the documentation site if docs change.
- [ ] Add Documentation standard to contributor guide.
- [x] Make a PR and notify shawn to enable github pages.

**Comment by HiceS** [comment]
Okay I already did this because it was so interesting,

Added the master/docs folder 

Found out how to use rustdocs or rather ` cargo docs `

**Comment by HiceS** [comment]
Updated readme with information on how to build the documentation and how to access the site.

**Comment by HiceS** [comment]
Added a rust build action as well that can generate the documentation in the future possibly.

**Comment by HiceS** [comment]
This is currently enabled to be used in the src code,

Still needs a documentation standard and additional code to build with CI ideally.

**Comment by HiceS** [comment]
Still need to create a standard for doing Documentation.

**Comment by HiceS** [comment]
I actually believe I finished and closed this up as far as the last PR goes, closing and moving to done for now.
